#include <cmath>
#include <njin.h>
#include <vector>

namespace {
njin::sound_handle beep;

// Sound generated by the game itself at startup, not read from a file.
void make_beep(njin::njin_ctx &ctx) {
  const njin::i32 sample_rate = 44100;
  const njin::i32 count = sample_rate / 5; // 0.2 seconds

  std::vector<njin::f32> samples((std::size_t)count);
  for (njin::i32 i = 0; i < count; i++) {
    const njin::f32 t = (njin::f32)i / (njin::f32)sample_rate;
    const njin::f32 fade = 1.0f - (njin::f32)i / (njin::f32)count; // fades out
    samples[(std::size_t)i] = 0.4f * fade * std::sin(2.0f * 3.14159265f * 880.0f * t);
  }

  // Mono, 32-bit float. The data is copied, so it is fine if `samples` is
  // destroyed right afterwards.
  beep = njin::sound_load_samples(ctx, samples.data(), count, sample_rate);
}

void setup(njin::njin_ctx &ctx) {
  njin::ecs_register(ctx, njin::phase_startup, make_beep);
}
} // namespace

njin::mod_desc procedural_audio_module() {
  return {.name = "procedural_audio", .setup = setup};
}
