# njin_embed_file(<out.cpp> <input> <symbol>)
#
# Turns a binary file into a C++ source that defines
#   namespace njin { extern const unsigned char <symbol>[]; extern const unsigned long long <symbol>_size; }
# at configure time. The output is only rewritten when its content changes, so
# an unchanged font does not rebuild the runtime, and CMake re-runs when the
# input file does.
function(njin_embed_file out input symbol)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
  file(READ "${input}" hex HEX)
  string(LENGTH "${hex}" hex_length)
  math(EXPR size "${hex_length} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  # CMake regular expressions have no {n}: repeat the pattern instead.
  string(REPEAT "0x[0-9a-f][0-9a-f]," 16 row_pattern)
  string(REGEX REPLACE "(${row_pattern})" "\\1\n" bytes "${bytes}")
  set(staging "${out}.staging")
  file(WRITE "${staging}"
       "// Generated by cmake/embed_file.cmake from ${input}. Do not edit.\n"
       "namespace njin {\n"
       "extern const unsigned char ${symbol}[];\n"
       "extern const unsigned long long ${symbol}_size;\n"
       "const unsigned char ${symbol}[] = {\n${bytes}\n};\n"
       "const unsigned long long ${symbol}_size = ${size}ull;\n"
       "} // namespace njin\n")
  configure_file("${staging}" "${out}" COPYONLY)
endfunction()
